---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: joshsizer-flux-root
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./linode/ystonedev/us-east/green
  prune: true
  sourceRef:
    kind: GitRepository
    name: joshsizer-flux-root
